// Shared between `installer.ts` (compiled and run as root on the Pi) and
// `set-secret.ts` (run locally to provision/rotate a secret). Both are
// compiled/run as standalone Deno programs, so this module is bundled into
// each rather than read at a shared path.
//
// Secret values themselves never live in a repository env file or in any
// plaintext file on the Pi. Each is encrypted at rest with `systemd-creds`,
// using a key that exists only on that machine, so the ciphertext under
// `SECRET_STORE_DIR` is useless without root access to that specific host.
import { pathExists } from "./step-helpers.ts";
import { ETC_ROOT } from "../utils/remote-paths.ts";
import { REMOTE_ENV_NAMES } from "../utils/environment.ts";
import { decodeBase64 } from "@std/encoding";

export interface SecretDef {
  readonly name: string;
  readonly label: string;
  /**
   * The name the credential is encrypted under, where it differs from the file
   * name. systemd checks the two match when a unit loads it.
   */
  readonly credentialName?: string;
  /**
   * Set where replacing the value makes existing data unreadable, so
   * `set-secret` asks for a typed confirmation before overwriting it.
   */
  readonly overwriteDestroysData?: boolean;
  /** Rejects a malformed value before it is stored. Throws on failure. */
  readonly validate?: (value: string) => void;
}

export const SECRET_STORE_DIR = `${ETC_ROOT}/credstore.encrypted`;

export const REQUIRED_SECRETS: readonly SecretDef[] = [
  { name: "cloudflare_tunnel_token", label: "Cloudflare Tunnel token" },
  { name: "cloudflare_zone_id", label: "Cloudflare Zone ID" },
  { name: "cloudflare_api_token", label: "Cloudflare API token" },
  { name: "geoip_account_id", label: "MaxMind GeoIP account ID" },
  { name: "geoip_license_key", label: "MaxMind GeoIP license key" },
];

export const OPTIONAL_SECRETS: readonly SecretDef[] = [
  {
    name: "otel_collector_export_authorization",
    label: "OpenTelemetry Collector Authorization header value",
  },
];

export const SECRETS: readonly SecretDef[] = [
  ...REQUIRED_SECRETS,
  ...OPTIONAL_SECRETS,
];

export function isSecretName(name: string): boolean {
  return SECRETS.some((secret) => secret.name === name);
}

export function credentialPath(name: string): string {
  return `${SECRET_STORE_DIR}/${name}.cred`;
}

// The name every environment's key is encrypted under. It is deliberately the
// same for all of them — systemd checks the name a credential was encrypted
// with against the one the unit asks for — while the *contents* of the two
// files are independent keys.
export const KV_ENCRYPTION_KEY_CREDENTIAL = "kv_encryption_key";

// Unlike the provider-issued secrets above, this key is generated on the Pi by
// the installer rather than entered by hand, and each environment gets its own
// file: prod's key cannot read staging's database, or the other way round.
export function kvEncryptionKeyPath(env: string): string {
  return credentialPath(`${KV_ENCRYPTION_KEY_CREDENTIAL}_${env}`);
}

const KV_ENCRYPTION_KEY_LENGTH = 32;

export function validateKvEncryptionKey(value: string): void {
  let bytes: Uint8Array;

  try {
    bytes = decodeBase64(value.trim());
  } catch {
    throw new Error(
      "The key must be base64, exactly as `systemd-creds decrypt` printed it.",
    );
  }

  if (bytes.length !== KV_ENCRYPTION_KEY_LENGTH) {
    throw new Error(
      `The key must decode to ${KV_ENCRYPTION_KEY_LENGTH} bytes, not ` +
        `${bytes.length}. This does not look like a KV encryption key.`,
    );
  }
}

// Deliberately outside `SECRETS`: these are generated by the installer, not
// entered by hand, and `ensureSecretsPresent` must not demand them. They are
// settable only to put a backed-up key back on a rebuilt machine — the one
// case where typing one in is the difference between readable and lost data.
export const KV_ENCRYPTION_SECRETS: readonly SecretDef[] = REMOTE_ENV_NAMES
  .map((env) => ({
    name: `${KV_ENCRYPTION_KEY_CREDENTIAL}_${env}`,
    label: `KV encryption key (${env})`,
    credentialName: KV_ENCRYPTION_KEY_CREDENTIAL,
    overwriteDestroysData: true,
    validate: validateKvEncryptionKey,
  }));

// Required provider-issued secrets (Cloudflare, MaxMind) are provisioned
// separately with `deno task set-secret <name>`, never uploaded in the
// installer's config file. This only checks they already exist.
export async function ensureSecretsPresent(): Promise<void> {
  const missing = [];
  for (const secret of REQUIRED_SECRETS) {
    if (!await pathExists(credentialPath(secret.name))) {
      missing.push(secret);
    }
  }
  if (missing.length === 0) return;

  const lines = missing
    .map((secret) => `  deno task set-secret ${secret.name}  # ${secret.label}`)
    .join("\n");
  throw new Error(
    `Missing ${missing.length} secret(s). Run the following from the ` +
      `laptop, then re-run setup-remote:\n${lines}`,
  );
}
