import { run } from "../../utils/run.ts";
import { REMOTE_ENV_NAMES } from "../../utils/environment.ts";
import {
  APP_GROUP,
  APP_USER,
  REMOTE_PORTS,
} from "../../utils/infrastructure.ts";
import { type Color } from "../constants.ts";
import { ETC_ROOT, SYSTEM_PATHS } from "../../utils/remote-paths.ts";
import { ensureFile, pathExists, type StepResult } from "../step-helpers.ts";
import { markAptUpdated } from "./apt.ts";

// ---------------------------------------------------------------------------
// Package (caddy apt repo)
// ---------------------------------------------------------------------------

export async function ensureCaddyRepoAndPackage(): Promise<StepResult> {
  const { code } = await run("dpkg", ["-s", "caddy"], {
    stdout: "piped",
    check: false,
  });
  if (code === 0) {
    return { label: 'Package "caddy"', changed: false };
  }

  const keyringPath =
    `${SYSTEM_PATHS.keyrings}/caddy-stable-archive-keyring.gpg`;
  const listPath = `${SYSTEM_PATHS.aptSources}/caddy-stable.list`;

  if (!await pathExists(keyringPath)) {
    await run(
      "bash",
      [
        "-c",
        `curl -1sLf 'https://dl.cloudsmith.io/public/caddy/stable/gpg.key' | ` +
        `gpg --dearmor -o ${keyringPath}`,
      ],
    );
  }

  if (!await pathExists(listPath)) {
    await run(
      "bash",
      [
        "-c",
        `curl -1sLf 'https://dl.cloudsmith.io/public/caddy/stable/debian.deb.txt' ` +
        `-o ${listPath}`,
      ],
    );
  }

  await run("apt-get", ["update"]);
  markAptUpdated();
  await run("apt-get", ["install", "-y", "caddy"]);

  return { label: 'Package "caddy"', changed: true, detail: "installed" };
}

// ---------------------------------------------------------------------------
// Caddy config (reverse proxy in front of the blue/green app instances)
// ---------------------------------------------------------------------------

// Generates the small per-env snippet Caddy `import`s, pointing at whichever
// color's port is currently active. Regenerated by the deployer on every
// cutover; only created here (if missing) so a fresh install has something
// valid to boot with.
function activeUpstreamSnippet(port: string): string {
  return [
    `reverse_proxy 127.0.0.1:${port} {`,
    // cloudflared already sets X-Forwarded-Proto based on the original
    // (HTTPS) request at Cloudflare's edge; Caddy's reverse_proxy would
    // otherwise overwrite it using the local (plain HTTP) connection it
    // received it over, breaking `httpsMid`'s redirect logic.
    "\theader_up X-Forwarded-Proto {http.request.header.X-Forwarded-Proto}",
    "}",
    "",
  ].join("\n");
}

export async function ensureCaddyConfig(): Promise<StepResult[]> {
  const results: StepResult[] = [];

  for (const env of REMOTE_ENV_NAMES) {
    const activeColorPath = `${ETC_ROOT}/${env}/active-color`;
    if (!await pathExists(activeColorPath)) {
      await ensureFile(
        activeColorPath,
        "blue\n",
        APP_USER,
        APP_GROUP,
        "644",
      );
      results.push({
        label: `active color (${env})`,
        changed: true,
        detail: "defaulted to blue",
      });
    } else {
      results.push({ label: `active color (${env})`, changed: false });
    }

    const activeColor = (await Deno.readTextFile(activeColorPath))
      .trim() as Color;
    const snippetPath = `${ETC_ROOT}/${env}/active-upstream.caddy`;
    const snippetResult = await ensureFile(
      snippetPath,
      activeUpstreamSnippet(REMOTE_PORTS[env][activeColor]),
      APP_USER,
      APP_GROUP,
      "644",
    );
    results.push({
      label: `Caddy upstream snippet (${env})`,
      changed: snippetResult.changed,
    });
  }

  const caddyfile = REMOTE_ENV_NAMES.map((env) =>
    [
      `:${REMOTE_PORTS[env].proxy} {`,
      `\timport ${ETC_ROOT}/${env}/active-upstream.caddy`,
      "}",
      "",
    ].join("\n")
  ).join("\n");

  const caddyfileResult = await ensureFile(
    SYSTEM_PATHS.caddyConfig,
    caddyfile,
    "root",
    "root",
    "644",
  );
  results.push({ label: "Caddyfile", changed: caddyfileResult.changed });

  const { code: enabledCode } = await run(
    "systemctl",
    ["is-enabled", "caddy"],
    { stdout: "piped", check: false },
  );
  const { code: activeCode } = await run(
    "systemctl",
    ["is-active", "caddy"],
    { stdout: "piped", check: false },
  );

  if (enabledCode !== 0 || activeCode !== 0) {
    await run("systemctl", ["enable", "--now", "caddy"]);
  } else {
    // Always reload (not just when a file changed): reloading with
    // unchanged, already-valid config is a cheap no-op, and this keeps the
    // running Caddy config in sync even after a prior run left it stale
    // (e.g. a mid-provisioning failure applied the files but not the
    // reload).
    await run("caddy", ["validate", "--config", SYSTEM_PATHS.caddyConfig], {
      check: false,
    });
    await run("systemctl", ["reload", "caddy"]);
  }

  return results;
}
