import { join } from "@std/path";
import { run } from "../utils/run.ts";

// Regenerates `aaguid.ts` and the icon SVGs in
// `src/features/passkeys/assets/icons` from the community-maintained
// https://github.com/passkeydeveloper/passkey-authenticator-aaguids list.
// Re-run this whenever a new authenticator should be recognized, then review
// the diff (new/renamed/removed authenticators, added/removed icons) before
// committing.

const SOURCE_URL =
  "https://raw.githubusercontent.com/passkeydeveloper/passkey-authenticator-aaguids/main/aaguid.json";

const AAGUID_FILE = join(
  import.meta.dirname!,
  "../../src/features/passkeys/aaguid.ts",
);
const ICONS_DIR = join(
  import.meta.dirname!,
  "../../src/features/passkeys/assets/icons",
);

// Entries in the source list that aren't real authenticators (pentesting
// tools, placeholder/test AAGUIDs), so they're excluded rather than shown as
// a passkey's authenticator.
const EXCLUDED_AAGUIDS = new Set([
  "c9cadfc9-89a9-489e-a25a-c7e86a4d5f15", // Burp Suite Navigation Recorder
  "6d212b28-a2c1-4638-b375-5932070f62e9", // "initial", a placeholder entry
  "9f8a3b2c-1d4e-4f6a-8b0c-2e1d3c4b5a69", // U2 Secured
]);

interface SourceEntry {
  name: string;
  icon_light?: string;
  icon_dark?: string;
}

function decodeSvgDataUri(aaguid: string, field: string, dataUri: string) {
  const match = dataUri.match(/^data:image\/svg\+xml;base64,(.+)$/);
  const base64 = match?.[1];

  if (!base64) {
    throw new Error(
      `${aaguid} (${field}) is not an SVG data URI, the source list's format may have changed: ${
        dataUri.slice(0, 40)
      }`,
    );
  }

  return atob(base64);
}

const response = await fetch(SOURCE_URL);

if (!response.ok) {
  throw new Error(`Failed to fetch ${SOURCE_URL}: ${response.status}`);
}

const source: Record<string, SourceEntry> = await response.json();

const entries = Object.entries(source)
  .filter(([aaguid]) => !EXCLUDED_AAGUIDS.has(aaguid))
  // Matches the existing file's order, which is by display name rather than
  // by AAGUID.
  .sort(([, a], [, b]) => a.name < b.name ? -1 : a.name > b.name ? 1 : 0);

const namesByAaguid = new Map(
  entries.map(([aaguid, entry]) => [aaguid, entry.name]),
);
const aaguidsWithoutIcon = entries
  .filter(([, entry]) => !entry.icon_light || !entry.icon_dark)
  .map(([aaguid, entry]) => [aaguid, entry.name] as const);

const namesLines = [...namesByAaguid].map(([aaguid, name]) =>
  `  ${JSON.stringify(aaguid)}: ${JSON.stringify(name)},`
).join("\n");
const withoutIconLines = aaguidsWithoutIcon.map(([aaguid, name]) =>
  `  ${JSON.stringify(aaguid)}, // ${name}`
).join("\n");

const fileContent = `\
// AAGUID → display name, used to name passkeys after the authenticator that
// created them. Curated from the community-maintained list at
// https://github.com/passkeydeveloper/passkey-authenticator-aaguids
// (aaguid.json; names verbatim). Non-authenticator entries (test keys,
// developer tools) are dropped; the all-zero AAGUID is intentionally absent
// so unknown authenticators fall through to the "Passkey •xxxx" fallback.
//
// Generated by \`deno task update-aaguids\` — do not hand-edit.
export const AAGUID_NAMES: Record<string, string> = {
${namesLines}
};

// AAGUIDs from the list above that the source repo has no icon for. Every
// other key is expected to have \`<aaguid>-light.svg\` and \`<aaguid>-dark.svg\`
// in \`./assets/icons\`, extracted from the same \`aaguid.json\`'s
// \`icon_light\` / \`icon_dark\` (base64 SVG data URIs).
export const AAGUIDS_WITHOUT_ICON = new Set([
${withoutIconLines}
]);
`;

await Deno.writeTextFile(AAGUID_FILE, fileContent);
await run("deno", ["fmt", AAGUID_FILE]);

// Icons: write the current set, then remove stale files left over from
// authenticators that were renamed, dropped, or lost their icon.
await Deno.mkdir(ICONS_DIR, { recursive: true });

const expectedIconFiles = new Set<string>();

for (const [aaguid, entry] of entries) {
  if (!entry.icon_light || !entry.icon_dark) {
    continue;
  }

  const lightFile = `${aaguid}-light.svg`;
  const darkFile = `${aaguid}-dark.svg`;

  await Deno.writeTextFile(
    join(ICONS_DIR, lightFile),
    decodeSvgDataUri(aaguid, "icon_light", entry.icon_light),
  );
  await Deno.writeTextFile(
    join(ICONS_DIR, darkFile),
    decodeSvgDataUri(aaguid, "icon_dark", entry.icon_dark),
  );
  expectedIconFiles.add(lightFile);
  expectedIconFiles.add(darkFile);
}

const AAGUID_ICON_FILENAME = /^[0-9a-f-]{36}-(?:light|dark)\.svg$/;

for await (const entry of Deno.readDir(ICONS_DIR)) {
  if (
    entry.isFile && AAGUID_ICON_FILENAME.test(entry.name) &&
    !expectedIconFiles.has(entry.name)
  ) {
    await Deno.remove(join(ICONS_DIR, entry.name));
    console.log(`Removed stale icon: ${entry.name}`);
  }
}

console.log(
  `Updated ${namesByAaguid.size} authenticators (${
    namesByAaguid.size - aaguidsWithoutIcon.length
  } with icons).`,
);
